trigger:
  - main
 
variables:
  - name: process.clean
    value: false
 
pool:
  name: Springboot-application  # Self-hosted agent pool name
 
stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: Build
        displayName: Build Maven Project
        steps:
          # Step 1: Checkout the repository
          - checkout: self
            clean: true
 
          # Step 2: Build Maven Project
          - task: Maven@4
            displayName: 'Maven Package'
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'clean package'
 
          # Step 3: Copy files to artifact staging directory
          - task: CopyFiles@2
            displayName: 'Copy Files to artifact staging directory'
            inputs:
              SourceFolder: '$(System.DefaultWorkingDirectory)'
              Contents: '**/target/*.?(war|jar)'
              TargetFolder: $(Build.ArtifactStagingDirectory)
 
          # Step 4: Publish Build Artifacts
          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact'
            inputs:
              pathToPublish: $(Build.ArtifactStagingDirectory)
              artifactName: SampleSpringBootBuild